-- Vivero NativaCR - Grupo 8
-- Esquema relacional (8 tablas) - Firebird 4
-- Migrado desde MariaDB para el Avance II (ver sql/mariadb_avance1/ y docs/migracion-firebird.md)

-- Ejecutar con: isql-fb -user SYSDBA -password '<password_sysdba>' -i 01_schema.sql
-- (la contrasena de SYSDBA vive solo en la VM, nunca en este repositorio)
CREATE DATABASE 'localhost:/var/lib/firebird/data/vivero_nativacr.fdb'
  PAGE_SIZE 8192
  DEFAULT CHARACTER SET UTF8;

CREATE TABLE zonas_biologicas (
  id_zona     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR(80)  NOT NULL UNIQUE,
  descripcion VARCHAR(255)
);

CREATE TABLE especies (
  id_especie        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_zona           INTEGER NOT NULL,
  nombre_cientifico VARCHAR(120) NOT NULL,
  nombre_comun      VARCHAR(80)  NOT NULL,
  precio_unitario   DECIMAL(10,2) NOT NULL CHECK (precio_unitario >= 0),
  descripcion       BLOB SUB_TYPE TEXT CHARACTER SET UTF8,
  CONSTRAINT fk_especies_zona
    FOREIGN KEY (id_zona) REFERENCES zonas_biologicas(id_zona)
);

CREATE TABLE invernaderos (
  id_invernadero INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre         VARCHAR(60)  NOT NULL UNIQUE,
  ubicacion      VARCHAR(120) NOT NULL,
  capacidad      INTEGER NOT NULL CHECK (capacidad > 0)
);

CREATE TABLE lotes (
  id_lote        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_especie     INTEGER NOT NULL,
  id_invernadero INTEGER NOT NULL,
  cantidad       INTEGER NOT NULL CHECK (cantidad >= 0),
  fecha_siembra  DATE NOT NULL,
  estado         VARCHAR(12) DEFAULT 'activo' NOT NULL,
  CONSTRAINT fk_lotes_especie
    FOREIGN KEY (id_especie) REFERENCES especies(id_especie),
  CONSTRAINT fk_lotes_invernadero
    FOREIGN KEY (id_invernadero) REFERENCES invernaderos(id_invernadero),
  CONSTRAINT ck_lotes_estado
    CHECK (estado IN ('activo','vendido','descartado'))
);

CREATE TABLE clientes (
  id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre     VARCHAR(100) NOT NULL,
  telefono   VARCHAR(20),
  correo     VARCHAR(120),
  tipo       VARCHAR(12) DEFAULT 'persona' NOT NULL,
  CONSTRAINT ck_clientes_tipo
    CHECK (tipo IN ('persona','institucion'))
);

CREATE TABLE pedidos (
  id_pedido    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente   INTEGER NOT NULL,
  fecha_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  estado       VARCHAR(12) DEFAULT 'pendiente' NOT NULL,
  total        DECIMAL(12,2) DEFAULT 0 NOT NULL CHECK (total >= 0),
  CONSTRAINT fk_pedidos_cliente
    FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente),
  CONSTRAINT ck_pedidos_estado
    CHECK (estado IN ('pendiente','confirmado','entregado','cancelado'))
);

CREATE TABLE detalle_pedido (
  id_detalle  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pedido   INTEGER NOT NULL,
  id_lote     INTEGER NOT NULL,
  cantidad    INTEGER NOT NULL CHECK (cantidad > 0),
  subtotal    DECIMAL(12,2) NOT NULL CHECK (subtotal >= 0),
  CONSTRAINT fk_detalle_pedido
    FOREIGN KEY (id_pedido) REFERENCES pedidos(id_pedido),
  CONSTRAINT fk_detalle_lote
    FOREIGN KEY (id_lote) REFERENCES lotes(id_lote),
  CONSTRAINT uq_pedido_lote UNIQUE (id_pedido, id_lote)
);

CREATE TABLE cuidados_lote (
  id_cuidado    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_lote       INTEGER NOT NULL,
  fecha_cuidado DATE NOT NULL,
  tipo_cuidado  VARCHAR(20) NOT NULL
                  CHECK (tipo_cuidado IN ('riego','fertilizacion','poda','control_plagas','trasplante')),
  observaciones VARCHAR(255),
  CONSTRAINT fk_cuidados_lote
    FOREIGN KEY (id_lote) REFERENCES lotes(id_lote)
);

CREATE INDEX idx_lotes_estado ON lotes(estado);
CREATE INDEX idx_pedidos_fecha ON pedidos(fecha_pedido);
CREATE INDEX idx_especies_comun ON especies(nombre_comun);
